;;; Automatically generated by ‘recentf’ on Sat Nov 19 07:58:30 2022.

(setq recentf-list
      '(

        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
