;;; Automatically generated by ‘recentf’ on Thu Nov  3 13:38:00 2022.

(setq recentf-list
      '(
        "/tmp/zshwEAxM1.zsh"
        "/home/raxit/Gargi.org"
        "/home/raxit/Downloads/core.org"
        "/home/raxit/cpp-mode.cpp"
        "/home/raxit/.emacs"
        "/home/raxit/.emacs.d/var/gamegrid-user-score/snake-scores"
        "/home/raxit/wrx/yaho.cpp"
        "/home/raxit/.emacs.d/etc/yasnippet/snippets/c++-mode/compi_structure"
        "/home/raxit/.emacs.d/etc/yasnippet/snippets/org-mode/src-elisp"
        "/home/raxit/.emacs.d/etc/yasnippet/snippets/org-mode/code"
        "/home/raxit/wrx/new.cpp"
        "/home/raxit/wrx/hello.cpp"
        "/home/raxit/wrx/org/todo.org"
        "/home/raxit/wrx/input.txt"
        "/home/raxit/.emacs.d/elpa/yasnippet-20200604.246/yasnippet.el"
        "/home/raxit/.emacs.d/var/gamegrid-user-score/tetris-scores"
        "/home/raxit/draco-emacs/init.org"
        "/home/raxit/.emacs.d/custom.el"
        "/home/raxit/.notes"
        "/home/raxit/.Xmodmap"
        "/home/raxit/url_list.txt"
        "/home/raxit/.cache/zsh/history"
        "/home/raxit/.config/mpv/mpv.conf"
        "/home/raxit/wrx/org/emacs-menual.org"
        "/home/raxit/wrx/org/org_user-menual.org"
        "/home/raxit/.config/yt-dlp/config"
        "/home/raxit/wrx/org/cheat_sheet.org"
        "/home/raxit/word/ytdl_uses.org"
        "/home/raxit/wrx/org/keyboard_shortcuts.org"
        "/usr/share/emacs/28.2/etc/HELLO"
        "/home/raxit/wrx/apple.cpp"
        "/home/raxit/wrx/org/text.org"
        "/home/raxit/wrx/org/evil_user.org"
        "/home/raxit/wrx/org/evil_treemacs_keybindings.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
