;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(buffer-name-history extended-command-history query-replace-history minibuffer-history file-name-history swiper-history ivy-history))
(setq buffer-name-history '(#(" SPEEDBAR" 0 9 (ivy-index 0)) #("README.org • .emacs.d" 0 21 (ivy-index 0)) #("emacs" 0 5 (ivy-index 3)) #("zoliky-emacs" 0 12 (ivy-index 10)) #("README.org • zoliky-emacs" 0 25 (ivy-index 11))))
(setq extended-command-history '(#("speedbar" 0 8 (ivy-index 0))))
(setq query-replace-history '("]" ")" "[" "(" "[]" "()"))
(setq file-name-history '(#("/home/raxit/emacs/zoliky-emacs/" 0 31 (ivy-index 2)) #("/home/raxit/.emacs.d/README.org" 0 31 (ivy-index 2)) #("/home/raxit/emacs/zoliky-emacs/README.org" 0 41 (ivy-index 3)) #("/home/raxit/emacs/" 0 18 (ivy-index 0)) #("/home/raxit/emacs/flinner.md" 0 28 (ivy-index 3)) #("/home/raxit/emacs/example.md" 0 28 (ivy-index 0)) "~/wrx/org/quotes.org" "~/.emacs.d/etc/yasnippet/snippets/org-mode/src" "~/.emacs.d/etc/yasnippet/snippets/org-mode/code"))
(setq swiper-history '(#("installi" 0 8 (ivy-index 0)) #("color" 0 5 (ivy-index 0)) #(".d?" 0 3 (ivy-index 1162)) #("setup-s" 0 7 (ivy-index 0)) #("dash" 0 4 (ivy-index 4))))
(setq ivy-history '(#("README.org • zoliky-emacs" 0 25 (ivy-index 1)) #("ef-tritanopia-light" 0 19 (ivy-index 3)) #("README.org • .emacs.d" 0 21 (ivy-index 1)) #("flinner.md" 0 10 (ivy-index 1)) #("example.md" 0 10 (ivy-index 1)) #("=) - Slightly Smiling Face (ascii)" 0 34 (ivy-index 0)) #(":D - Smiling Face With Open Mouth (ascii)" 0 41 (ivy-index 19)) #(":smirk-cat: - Cat Face With Wry Smile (github)" 0 46 (ivy-index 2)) #("😏 - Smirking Face (unicode)" 0 27 (ivy-index 0)) #("✨ - Sparkles (unicode)" 0 22 (ivy-index 1)) #("end_cen" 0 7 (ivy-index 0)) "END_CENTER" #("begin_c" 0 7 (ivy-index 0)) "BEGIN_CENTER" #("💬 - Speech Balloon (unicode)" 0 28 (ivy-index 2)) #(":speech-balloon: - Speech Balloon (github)" 0 42 (ivy-index 3)) #("init.el" 0 7 (ivy-index 1)) #("*Ibuffer*" 0 9 (ivy-index 1)) #("doom-gruvbox-light" 0 18 (ivy-index 1))))
(setq search-ring 'nil)
(setq regexp-search-ring '("installi" "color" "\\.d?" "setup-s" "dash"))
