;;; Automatically generated by ‘recentf’ on Fri Oct 28 21:03:19 2022.

(setq recentf-list
      '(
        "/home/raxit/.emacs"
        "/home/raxit/draco-emacs/init.org"
        "/home/raxit/.notes"
        "/home/raxit/wrx/hello.cpp"
        "/home/raxit/.Xmodmap"
        "/home/raxit/url_list.txt"
        "/home/raxit/Downloads/core.org"
        "/home/raxit/.cache/zsh/history"
        "/home/raxit/.config/mpv/mpv.conf"
        "/home/raxit/wrx/org/emacs-menual.org"
        "/home/raxit/wrx/org/org_user-menual.org"
        "/home/raxit/.config/yt-dlp/config"
        "/home/raxit/wrx/org/cheat_sheet.org"
        "/home/raxit/word/ytdl_uses.org"
        "/home/raxit/wrx/org/keyboard_shortcuts.org"
        "/usr/share/emacs/28.2/etc/HELLO"
        "/home/raxit/wrx/org/todo.org"
        "/home/raxit/wrx/apple.cpp"
        "/home/raxit/wrx/org/text.org"
        "/home/raxit/wrx/org/evil_user.org"
        "/home/raxit/wrx/org/evil_treemacs_keybindings.org"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
