;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(empty-history counsel-M-x-history swiper-history))
(setq counsel-M-x-history '(#("pack au" 0 7 (ivy-index 0)) "package-autoremove" #("lis pac" 0 7 (ivy-index 0)) "list-packages"))
(setq swiper-history '(#("'pack " 0 6 (ivy-index 0)) #("lsp-" 0 4 (ivy-index 0))))
(setq kill-ring 'nil)
(setq search-ring 'nil)
(setq regexp-search-ring '("'pack" "lsp-"))
